function transformKeysToRegExp(variable){
    return Object.keys(variable).filter(key => key !== '')
}

window.parameterTypes = {
    tableTypes: transformKeysToRegExp(window.tableMappings),
    baseElement: transformKeysToRegExp(window.elementChoices),
    toDoTableTypes: transformKeysToRegExp(window.to_do_list_tables),
    labeledElement: ['button', 'link'],
    projectType: [
        'Practice / Just for fun',
        'Operational Support',
        'Research',
        'Quality Improvement',
        'Other',
    ],
    enableDisable: ['enable', 'disable'],
    repeatability: ['enabled', 'disabled', 'modifiable', 'unchangeable'],
    confirmation: ['accept', 'cancel'],
    ordering: ['ascending', 'descending'],
    dataViewingRights: ['No Access', 'Read Only', 'View & Edit', 'Edit survey responses'],
    editSurveyRights: [
        '',
        ' with Edit survey responses checked',
        ' with Edit survey responses unchecked',
        '',
    ],
    see: ['should see', 'see'],
    check: ['checked', 'unchecked'],
    addField: ['Add Field', 'Add Matrix of Fields', 'Import from Field Bank'],
    addEditField: ['Add New Field', 'Edit Field'],
    addOrSelect: ['add', 'select'],
    userRightAction: ['add', 'remove'],
    editField: ['Edit', 'Branching Logic', 'Copy', 'Move', 'Delete Field'],
    editEvent: ['Edit', 'Delete'],
    fieldType: [
        'Text Box',
        'Notes Box',
        'Drop-down List',
        'Radio Buttons',
        'Checkboxes',
        'Yes - No',
        'True - False',
        'Signature',
        'File Upload',
        'Slider',
        'Descriptive Text',
        'Begin New Section',
        'Calculated Field',
    ],
    cellAction: [
        ' and click the new instance link',
        ' and click on the bubble',
        ' and click the repeating instrument bubble for the first instance',
        ' and click the repeating instrument bubble for the second instance',
        ' and click the repeating instrument bubble for the third instance',
        '',
    ],
    select: ['selected', 'unselected'],
    instrumentSaveOptions: [
        'Save & Stay',
        'Save & Exit Record',
        'Save & Go To Next Record',
        'Save & Exit Form',
        'Save & Go To Next Form',
        'Save & Go To Next Instance',
        'Save & Add New Instance',
    ],
    enterType: ['verify', 'enter', 'clear field and enter'],
    clickType: ['click on', 'check', 'uncheck'],
    elmType: ['input', 'list item', 'checkbox', 'span'],
    dropdownType: ['dropdown', 'multiselect'],
    labeledExactly: ['labeled', 'labeled exactly'],
    saveButtonRouteMonitoring: [
        '',
        ' on the dialog box for the Repeatable Instruments and Events module',
        ' on the Designate Instruments for My Events page',
        ' on the Online Designer page',
        ' and cancel the confirmation window',
        ' and accept the confirmation window',
        ' in the dialog box to request a change in project status',
        ' to rename an instrument',
        ' in the "Add New Field" dialog box',
        ' in the "Edit Field" dialog box',
        '',
    ],
    tableName: ['', ' of the User Rights table', ' of the Reports table'],
    linkNames: ['link', 'tab', 'instrument'],
    toDoRequestTypes: ['Move to prod', 'Approve draft changes', 'Copy project'],
    toDoTableIcons: [
        'process request',
        'get more information',
        'add or edit a comment',
        'Move to low priority section',
        'archive request notification',
    ],
    iframeVisibility: ['', ' in the iframe'],
    projectStatus: ['Production', 'Development', 'Analysis/Cleanup'],
    moveToProductionButton: ['Create Project', 'Send Request'],
    checkBoxRadio: ['checkbox', 'radio'],
    notSee: ['not '],
    headerOrNot: ['header and '],
    toDownloadFile: [' to download a file'],
    beforeAfter: ['before', 'after'],
    recordIDEvent: ['record ID', 'event'],
    timeType: ['seconds', 'second', 'minutes', 'minute']
}